name: 构建 Tauri 应用 (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [trigger-tauri-build]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      # Tauri CLI 用于缓存和加速构建
      CI: true
      TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
      TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 安装 Rust 稳定版
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 显示 Rust/Cargo 版本信息
        run: |
          rustc -V
          cargo -V
        shell: pwsh

      - name: 安装前端依赖
        run: pnpm install --frozen-lockfile
        shell: pwsh

      - name: 构建 Tauri 应用
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_BUNDLE_TARGETS: app
        with:
          includeDebug: false
          tauriScript: 'pnpm tauri'

      - name: 重命名可执行文件（添加日期和分钟数）
        run: |
          $date = Get-Date -Format "yyyyMMdd"
          $now = Get-Date
          $midnight = $now.Date
          $minutes = [int]($now - $midnight).TotalMinutes
          Get-ChildItem "src-tauri/target/release/*.exe" | 
          ForEach-Object {
            $newName = $_.BaseName + "-$date-" + $minutes + $_.Extension
            Rename-Item $_.FullName -NewName $newName
          }
        shell: pwsh

      - name: 上传构建产物
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-build
          path: src-tauri/target/release/*.exe

